services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: darksense_app
        ports:
            - '8080:80'
            - '3000:3000'
        volumes:
            - ./:/var/www/html
